import type { Metadata } from "next";
// import "./globals.css";
import { Roboto } from "next/font/google";
import { NextAppProvider } from "@toolpad/core/nextjs";
import LinearProgress from "@mui/material/LinearProgress";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import React from "react";
import { NAVIGATION } from "./navigation";
import Image from "next/image";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.variable} suppressHydrationWarning>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <React.Suspense fallback={<LinearProgress />}>
            <NextAppProvider
              navigation={NAVIGATION.map((item) => ({
                ...item,
                icon: item.icon ? <item.icon /> : null, // Render icon only when needed
              }))}
              branding={{
                logo: <Image src="/assets/logo.png" alt="MUI logo" width={50} height={35} />,
                title: 'AMBIL NOMOR SPPD',
                homeUrl: '/',
              }}
            >
              {children}
            </NextAppProvider>
          </React.Suspense>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
